language: java

sudo: required

jdk:
    - oraclejdk8

install:
    - sudo apt-get update && sudo apt-get install oracle-java8-installer
    - java -version

script:
    - gradle assemble
    - [ ! -d src/generated/java/ch ] && echo Filenotfound! || echo Filefound:D
    - gradle test
