language: java

jdk:
  - oraclejdk8

script:
  - gradle assemble
  - gradle test
  
addons:
  apt:
    packages:
      - oracle-java8-installer

notifications:
  email: false
  webhooks: 
    urls: http://n.ethz.ch/student/batim/php/sco.php
    on_success: always
    on_failure: always
    on_start: always
    
