language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

script:
  - gradle assemble
  - gradle test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/04381be2cac51ec9fbc2
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always    # options: [always|never|change] default: always

#deploy:
#  skip_cleanup: true
#  provider: script
#  script: gradle deploy

env:
  global:
  - secure: dburHpQtREfwIsBZCUIw0uga1h0UZdinSH4yOLWkuYs7d1+v9kBsY60G1tj4pkZC76hGv3JEyq8CKdUz0QokrrQDlyX1rWtmhtGL0GFrVsvxd9XDALHukKD6PMa7mc2b4N0oKyx2MrtErO0Auq6VKUmpK3sHnKk/iTBxnla4M0wZFiuZ9aiQxgQ3lKqyd27/WPJM6ZF9LQ+94pjxNaildoufZtewzSxlvh+n0dDa+z9n5YrUjXGv10Mhq3ImctWcaWGe9zVaCzJiGNf3sKEcTrCFKvyCcckCj8fHVKzZsq0+zRksrqPWj+t+1a0zhBzSRJz8sKjS2l9+SWwukBDoJZ6nI9tIJivXh0OSHuDOxMndirthP967SZW9syAVcBIfoqmbAGrANVHc+v3Yy+0qqOu0Che/wYz3SbZZb7D8TUpmd3sZz3BdW/T/HX4gUosD9kCGzt6Mo5J+wWPXMTI3rkzMe1bga3qRe5TMJ4fyxLQyPWGb+Mi6V9vwUM067K169arvEYPWxr9DxtLW98ts+waXHeLR9LEXtmOEMmqNjcdSaJQx/5bVw4QuaRGsOS1GTppVmkcNorff8rVSdK3YDm3R4wjduHATtE2uyFSR+OseDySDGqEcgZwIVepXnY7rhiD2zaWGKGSCWC/pO5UX80mBeYnsiNTCHf/jPHx25xI=
  - secure: HWmUuWjskxyjFXlFd8LbBwOSSSC7+XM3IoUGsyZ3aPlXPS2zVxShNzg8R3t16VXVtTT2Xigs84cUjib4T61gWmdPF7CjvrVpRUAsAvIQMIXsP2BrHsOfSyvOOzJlMhi4TfjdjsCa4ixATJ8EkAoueJdCzAb1hGcEzv4AvF7d+CKebizw3eVCG9ELymkq0bTFHz+cH58vrcxj807lHFn4WaRuh7XBtttBq5ptTANyGPwP/3Oh3rLHgRsS8QurL2M3LXO+h6i9LQFMCtjI/fMiaJ28Fkm5hmXBMeKi/++Hgdz1g92HmYhxem+b9JGJ9oZfUIzchRdAC4RA+uSPjbfTg6Xa6Ezwm+LeqVLXBud0rMGARBChtR+pdFO3rDl2t9obZHSFuHZGudqqCUlpjCT6YNft+QSTzwupAIKO9OyNr+sTiwkMwpGwIy+HTKDZOcmyiUKxVnI/JfIIly7kxRlDWPq67+T6Ent6m4TF5wZ/talUz29TLuiZ4n4Iiu/0v0jok6WXyjlHLXKTdkWccOZHsN645P0OkvqN6zrsS4Vm2KgJ4rPzViK8JhGKzKqdPRqu07yKVsWQQtX1dhh5YgZkYLRuXq1xaT54SFNO4XnX8iQowgQMFDn8vK4igPClZaiyWN4age/5PQfKgSzQ56i4B7GTd5lrIYrkzjztHiel3TU=
  - secure: Rh8qe5HCMA0D/5/PwjQlqLS8MYFYPVYJlsxim/y9Sj+P7ZJuq00rJvsdcGzvNuJGo7z3mXs2bAFnQogSZG06Bwz+CHt26K9WRAcWrBEB4ZXJW0w7qAm/rAv5WinMtsyzXXX4QJpBYm9C0fqkxQlLbeVvDLYFWBCAh6Rd8xiIVZXFIBou26/NVZfT3mqNf1Z9FkA5AA07R+SXCEjbT4y8uAnVwcqqPlpfUeiJGtX9d7uLaq+i5N+Rp9+k/++gKUQVMIras5kgoT/DvDWClcU18ge3EcYLVxIOvPMOgbEUCq37TdCe7yNjZxUqz8xUMKnvozZax8EH+cLIvCTRFKfZdgYsycT8ycamzCgSVEInVAepDMuMXTrAAU6wf9erstWSj4Lm6t3ECL60v+xS/haXg0ZJbEBUi3VXxcA+IIEJpjtC3D5/B2ZJxWb9xjQiZYb1RSqq8bRwF07NGCGrr99/36E44tb7laIBohGxayRlc960Kmtl/B0gP9ksjiu7z1xX/TeM2uSldVf/tljoo7bD13+RHgMT2W6qLunTwcgai5B2pG8wqmlZrFcRcFDKMSqGFVHuEGnnuWMgv5Tbm8FciG/nktYoUNxP9HiOmrXmd210XhXHaQ7XwmKDuGyAcfBOKcPjCQXKXadCB98LGXRAiaZz8j8eYLa/xg+lAaG5aeY=
  - secure: TYo6ggicBWLsRub6cwIBEehujIairFK3Z0XL03xk/bnHxwcwQXK21PeM/Btk9uZVgMYb7eHW9KyK306Nhm55UdJ4V91mzXr4ckFJ0/2ho14jnKKHKZ+RRbLkbBExqEt+7ehOimyrRsoWhqbTG7c9gwdaaVMD6/U8hMftxXTVK+mpdVjYfypduosNWGBG1mxRPwcpZWCPzx4qao4tBt/Lg3u8eIy8fMJKuio9L+M2BYRq7TcMtQJPDeYq+vwRbwhXY0HzOYoHkImBJ3fSpTkJRYAfBZPMivmI5eA39Eq45EZPIBjIE8y13iAG71rLfKBRSINHPDd3zCQyhgMZbL7BnL9JmtS9Ofm9FHwXq6OBF2Ge50DTi+4gp5TyJqwLrV7egfgrEXumBiaCHweBgqc3m5aEUVuIW9mh0vvZJsau324w0MmZWwaB/QUyNz7BCLPvk8XESXSMpZ7A9WLSF7NhQ9VP9GfLzSb/iTr9UdP4SbQlb+cBBNr7bPlWN0X3t39LTIFZE5M6PtnlJZsoqPg35soit/ytP2/LeYyLW2Y0KZ48xDPnomWgt/i7/lLDVM4LTA8tYSqAG6/KW75XAXM5F7oLPY3CZNwBJRTyDjwSXo+KE8jq6Z2N3LcRLwRdq5ewWCowpObaUpzc2QLMsHNI00oqBSrfKCQS6ajVt4RTdv0=
